name: Unity Android arm64 Build

on:
  push:
    branches:
      - android
  pull_request:
    branches:
      - android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Unity Library
      uses: actions/cache@v4
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: | 
          Library-

    - name: Activate Unity License
      uses: game-ci/unity-activate@v4
      env:
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

    - name: Build Android arm64 APK
      uses: game-ci/unity-build@v4
      with:
        targetPlatform: Android
        buildMethod: BuildScript.PerformBuild
        buildArguments: -architecture arm64

    - name: Upload arm64 APK
      uses: actions/upload-artifact@v4
      with:
        name: Android-arm64-APK
        path: build/Android/arm64/*.apk
