name: Actions 😎

on:
  push:
    branches:
      - android
  pull_request:
    branches:
      - android
  workflow_dispatch:

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build Android arm64 APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildMethod: MajdataPlay.Editor.CustomBuild.BuildRelease
          args: -buildTarget Android -architecture arm64 -customBuildPath build/Android/MajdataPlay.apk -customBuildName MajdataPlay.apk
          outputPath: build/Android
          buildName: MajdataPlay.apk

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Android-arm64-APK
          path: build/Android/MajdataPlay.apk
